In [1]:
#!pip install numpy
#!pip3 install numpy

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,5,6]
arr = np.array(list)
print(list,type(list))
print(arr,type(arr))

<class 'list'> <class 'type'>
<class 'list'> <class 'numpy.ndarray'>


In [4]:
import time

size = 1_000_000

py_list = list(range(size))  # works fine now
start = time.time()
list1 = [i*i for i in py_list]
end = time.time()

print(f"Python list time = {end-start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"NumPy time = {end-start} seconds")


Python list time = 0.09662699699401855 seconds
NumPy time = 0.001998424530029297 seconds


In [7]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)}bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000bytes
numpy array size = 4000000 bytes


In [ ]:
import numpy as np

In [16]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)
arr2 = np.array([1,2,3,"asfbc"])
print(arr2,type(arr2),arr2.dtype)
print(arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' 'asfbc'] <class 'numpy.ndarray'> <U11
(4,)


In [22]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr3,arr3.dtype,arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] int32 (4, 3)


In [32]:
#create from scratch
arr4 = np.zeros((2,3),dtype="int64") #prefil with zero's
print(arr4,arr4.shape,arr.dtype)

[[0 0 0]
 [0 0 0]] (2, 3) int32


In [33]:
#create from scratch
arr4 = np.ones((2,3),dtype="int64") #prefil with zero's
print(arr4,arr4.shape,arr.dtype)

[[1 1 1]
 [1 1 1]] (2, 3) int32


In [34]:
#create from scratch
arr4 = np.zeros((2, ),dtype="int64") #prefil with zero's
print(arr4,arr4.shape,arr.dtype)

[0 0] (2,) int32


In [35]:
arr5 = np.full((3,4),100)#prefil with val
print(arr5)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [36]:
arr5 = np.eye(3) #identity matrix
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
arr5 = np.arange(1,11)
arr6 = np.arange(0,11,2)
print(arr5,arr5.shape) 
print(arr6,arr6.shape) 

[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 0  2  4  6  8 10] (6,)


In [46]:
arr7 = np.linspace(0,100,5) #evenly spaced arrays
print(arr7,arr7.shape)

[  0.  25.  50.  75. 100.] (5,)


In [53]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)#dimension
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [3]:
#operations
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped = arr.reshape((3,2))
print(reshaped,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (2, 3)


In [4]:
flatten_arr = arr.flatten()
print(flatten_arr,flatten_arr.shape)

[1 2 3 4 5 6] (6,)


In [7]:
#Indexing
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

3


In [8]:
#fancy indexing
arr = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [9]:
#boolean indexing

print(arr[arr>3])

[4 5 6]


In [11]:
#even values
print(arr[arr%2 ==0])
#odd values
print(arr[arr%2!=0])

[2 4 6]
[1 3 5]


In [14]:
#slicing
print(arr[1:4])
print(arr[1:])
print(arr[1::2])

[2 3 4]
[2 3 4 5 6]
[2 4 6]


In [16]:
#copy in list vs view 
nums =[1,2,3,4,5]
#list
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [21]:
nums1=np.array([1,2,3,4,5])
#view
sub_list = nums1[1:3]
sub_list2 = nums1[1:3].copy()
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums1)
#there is difference between 

[2 3]
[200   3]
[  1 200   3   4   5]


In [36]:
#data types

arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5.0])
arr2 = np.array([1,2,3,"4"])
arr3 = np.array([5+1j,5-3j])
print(arr,arr.dtype)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
print(arr3,arr3.dtype)
print(arr3[0]+arr3[1])
arr4 = np.array([True])
print(arr4,arr4.dtype)

[1 2 3 4 5] int32
[1. 2. 3. 4. 5.] float64
['1' '2' '3' '4'] <U11
[5.+1.j 5.-3.j] complex128
(10-2j)
[ True] bool


In [38]:
arr = np.array(["prime",{1,2,3},3.14])
print(arr,arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [44]:
#multi-dimensional array
# we can use in images ( black and white, colorful), chess game etc.
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
            
sum_of_cols = np.sum(arr2D , axis =0)
print(sum_of_cols)
             
sum_of_rows = np.sum(arr2D , axis =1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [50]:
#3D
arr3D = np.array([[[1,2],[3,4],[4,5]],[[7,8],[10,11],[11,12]]]) #2*3*2

In [52]:
print(arr3D,arr3D.shape)
print(arr[0,1,1])

[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[ 7  8]
  [10 11]
  [11 12]]] (2, 3, 2)
4


In [55]:
# slicing
print(arr3D[:,0,:])
print(arr3D[:,:,0])
arr3D[:,:,0] =99
print(arr3D)

[[1 2]
 [7 8]]
[[ 1  3  4]
 [ 7 10 11]]
[[[99  2]
  [99  4]
  [99  5]]

 [[99  8]
  [99 11]
  [99 12]]]


In [11]:
#vectorization
arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
arr2 = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr ** 2)
print(arr + arr1)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [12]:
#broadcasting
# [1,2,3,4] + 5 
print(arr + 5)
print(arr + arr1)
print(arr1 + arr2 , arr1.shape,arr2.shape)

[ 6  7  8  9 10]
[ 7  9 11 13 15]
[[12 14 16 18 20]
 [ 7  9 11 13 15]] (5,) (2, 5)


In [16]:
#Normalization
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [19]:
#mathematical function
arr = np.array([1,2,3,4,5])
#aggregation
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
3.0
2.0


In [24]:
#power function
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))



[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [25]:
#log
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [29]:
#rounding
print(np.round(3.2))
print(np.ceil(3.2))
print(np.floor(3.2))
print(np.trunc(3.230))
print(np.unique(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5]


In [31]:
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))



[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
